/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
          "on-tertiary": "#ffffff",
          "inverse-primary": "#ffb4a8",
          "secondary-fixed": "#ffdea6",
          "on-secondary-fixed-variant": "#5d4200",
          "on-primary-container": "#ffdad4",
          "on-tertiary-container": "#4c3f00",
          "primary-container": "#cc0000",
          "on-primary-fixed-variant": "#930000",
          "tertiary-fixed-dim": "#e9c400",
          "on-surface": "#1a1c1c",
          "surface-container-high": "#e9e8e7",
          "error-container": "#ffdad6",
          "on-primary": "#ffffff",
          "surface-bright": "#faf9f8",
          "on-secondary-fixed": "#271900",
          "on-tertiary-fixed-variant": "#544600",
          "surface-dim": "#dadad9",
          "surface-container-highest": "#e3e2e1",
          "on-secondary-container": "#715000",
          "primary-fixed": "#ffdad4",
          "tertiary-container": "#c9a900",
          "secondary": "#7b5800",
          "tertiary": "#705d00",
          "on-secondary": "#ffffff",
          "surface": "#faf9f8",
          "secondary-fixed-dim": "#f7bd48",
          "inverse-surface": "#2f3130",
          "surface-tint": "#c00000",
          "surface-container-lowest": "#ffffff",
          "error": "#ba1a1a",
          "on-surface-variant": "#5e3f3a",
          "tertiary-fixed": "#ffe16d",
          "primary-fixed-dim": "#ffb4a8",
          "outline": "#926e69",
          "inverse-on-surface": "#f1f0f0",
          "secondary-container": "#fdc34d",
          "surface-container-low": "#f4f3f2",
          "on-error": "#ffffff",
          "on-primary-fixed": "#410000",
          "on-background": "#1a1c1c",
          "surface-variant": "#e3e2e1",
          "background": "#faf9f8",
          "primary": "#9e0000",
          "on-tertiary-fixed": "#221b00",
          "outline-variant": "#e8bdb6",
          "on-error-container": "#93000a",
          "surface-container": "#eeeeed"
      },
      fontFamily: {
          "headline": ["Noto Serif", "serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
